// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Product.Inventory.Api;

#nullable disable

namespace Product.Inventory.Api.Migrations
{
	[DbContext(typeof(ProductContext))]
	[Migration("20240929173935_Initial Migration")]
	partial class InitialMigration
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "8.0.8")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.HasSequence<int>("product_id_seq")
				.StartsAt(100000L)
				.HasMin(100000L)
				.HasMax(999999L)
				.IsCyclic();

			modelBuilder.Entity("Product.Inventory.Api.Product", b =>
				{
					b.Property<int>("ProductId")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer")
						.HasDefaultValueSql("nextval('product_id_seq')");

					b.Property<string>("Category")
						.HasMaxLength(50)
						.HasColumnType("character varying(50)");

					b.Property<string>("Description")
						.HasMaxLength(500)
						.HasColumnType("character varying(500)");

					b.Property<string>("Name")
						.IsRequired()
						.HasMaxLength(100)
						.HasColumnType("character varying(100)");

					b.Property<decimal?>("Price")
						.HasColumnType("decimal(18, 2)");

					b.Property<int?>("Quantity")
						.HasColumnType("integer");

					b.Property<decimal?>("Rating")
						.HasColumnType("numeric");

					b.HasKey("ProductId");

					b.ToTable("Products");
				});
#pragma warning restore 612, 618
		}
	}
}
